---
- name: Installing System Packages (RHEL/CentOS 6+)
  yum: 
    name=libselinux-python 
    state=installed

- name: Disabling SELinux (RHEL/CentOS 6+)
  selinux:
    state=disabled 

- name: Bootstraping Download Directory for RADIUSDesk Sources (RHEL/CentOS 6+)
  file:
    path={{ temp_src_dir }}
    state=directory
    mode=0777
 
- name: Ensuring Apache is not installed (RHEL/CentOS 6+)
  yum:
    name={{ apache_pkg_name }}
    state=absent

- name: Installing EPEL Repo for RadiusDesk (RHEL/CentOS 6+)
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: installed

- name: Installing REMI Repo for RadiusDesk (RHEL/CentOS 6+)
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: installed

- name: Installing Nginx (RHEL/CentOS 6+)
  yum:
    name={{ nginx_pkg_name }}
    state=installed

- name: Installing PHP packages (RHEL/CentOS 6+)
  yum:
    name={{ item }}
    state=latest
    update_cache=yes
    enablerepo="remi,remi-php56"
  with_items: "{{ rd_php5_pkgs }}"

- name: Installing RadiusDesk packages (RHEL/CentOS 6+)
  yum:
    name={{ item }}
    state=installed
  with_items: "{{ rd_pkgs }}"
  notify:
    - Start Nginx
    - Start PHP-FPM

- name: Configuring PHP-FPM to use UNIX sockets (RHEL/CentOS 6+)
  template:
    src="nginx/php_fpm.www.conf.j2"
    dest={{ php_fpm_config }}

- name: Configuring Nginx to use UNIX sockets (RHEL/CentOS 6+)
  template:
    src="nginx/nginx.default.conf.j2"
    dest={{ nginx_default_config }}

- name: Configuring Nginx for RadiusDesk Web Compression (RHEL/CentOS 6+)
  template:
    src="nginx/nginx.conf.j2"
    dest={{ nginx_config }}
  notify:
    - Restart Nginx
    - Restart PHP-FPM

- name: Downloading CakePHP Source from Github (RHEL/CentOS 6+)
  git: 
    dest={{ temp_src_dir }}/cake2
    repo={{ cakephp_git_repo }}
    update=no
    version=2.7.9

- name: Copying CakePHP Source to Webroot (RHEL/CentOS 6+)
  shell: cp -a {{ temp_src_dir | quote }}/cake2 {{ nginx_webroot | quote }}/cake2

- name: Downloading RadiusDesk CakePHP Source from Subversion (RHEL/CentOS 6+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_cake_svn_repo }} {{ temp_src_dir }}/rd_cake

- name: Copying RadiusDesk CakePHP App Source to Webroot (RHEL/CentOS 6+)
  shell: cp -a {{ temp_src_dir | quote }}/rd_cake {{ nginx_webroot | quote }}/cake2/

- name: Downloading RadiusDesk CakePHP 3 Source from Subversion (RHEL/CentOS 6+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_cake3_svn_repo }} {{ temp_src_dir }}/cake3

- name: Copying RadiusDesk CakePHP 3 Source to Webroot (RHEL/CentOS 6+)
  shell: cp -a {{ temp_src_dir | quote }}/cake3 {{ nginx_webroot | quote }}/cake3

- name: Downloading RadiusDesk Viewer Source from Subversion (RHEL/CentOS 6+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_svn_repo }} {{ temp_src_dir }}/rd

- name: Copying RadiusDesk Viewer Source to Webroot (RHEL/CentOS 6+)
  shell: cp -a {{ temp_src_dir | quote }}/rd {{ nginx_webroot | quote }}/

- name: Downloading RadiusDesk Login Source from Subversion (RHEL/CentOS 6+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_login_svn_repo }} {{ temp_src_dir }}/login

- name: Downloading Dynamic Login Pages Subversion (RHEL/CentOS 6+)
  shell: svn checkout svn://dvdwalt@svn.code.sf.net/p/radiusdesk/code/trunk/rd_login /usr/share/nginx/html/rd_login
  
- name: Copying RadiusDesk Login Source webroot (RHEL/CentOS 6+)
  shell: cp -a {{ temp_src_dir | quote }}/login {{ nginx_webroot | quote }}/

- name: Configuring UAM Service for RadiusDesk Login (RHEL/CentOS 6+)
  template:
    dest="{{ nginx_webroot }}/login/services/uam.php"
    src="rd/uam.php.j2"

- name: Checking if we already downloaded ExtJS 6.2 sources (RHEL/CentOS 6+)
  stat:
    path="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
  register: extjs_src

- name: Downloading ExtJS 6.2 sources from Subversion (RHEL/CentOS 6+)
  get_url:
    url={{ extjs_62_src_url }}
    dest="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
    validate_certs=no
  when: "extjs_src.stat.exists == False or extjs_src.stat.md5 != '{{ extjs_62_src_md5_sum }}'"

- name: Extracting ExtJS 6.2 archive for RadiusDesk Viewer (RHEL/CentOS 6+)
  unarchive:
    src="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
    dest={{ nginx_webroot }}/rd/
    owner={{ web_user }}
    group={{ web_group }}
    mode=0664
    copy=no

- name: Correcting Webroot ownership and permissions (RHEL/CentOS 6+)
  file:
    path={{ nginx_webroot }}
    owner={{ web_user }}
    group={{ web_group }}
    mode=0775
    state=directory
    recurse=yes

- name: Fix PHP Default Timezone
  lineinfile: 
    dest="{{ php_config_file }}"
    line='date.timezone = {{ php_timezone }}'
    regexp='^;date.timezone'

- name: Ensuring Nginx is Started (RHEL/CentOS 6+)
  service:
    name={{ nginx_service_name }}
    state=started

- name: Ensuring PHP-FPM is Started (RHEL/CentOS 6+)
  service:
    name={{ php_fpm_service_name }}
    state=started

- name: Configuring RadiusDesk Cron Jobs (RHEL/CentOS 6+)
  template:
    src="cron/cron.j2"
    dest="/etc/cron.d/rd"

- name: Disabling MySQL 5.6+ Strict Mode (RHEL/CentOS 6+)
  lineinfile:
    dest: /etc/my.cnf
    regexp: '^sql_mode='
    line: 'sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

- name: Ensuring MySQL is Started (RHEL/CentOS 6+)
  service:
    name={{ mysql_service_name }}
    state=started

- name: Ensuring MySQL Root password has been set (RHEL/CentOS 6+)
  stat:
    path={{ mysql_my_cnf }}
  register: mysql_conf

- name: Changing MySQL Root password (RHEL/CentOS 6+)
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    state=present
  with_items: "{{ mysql_db_hosts }}"
  notify:
    - Restart MySQL
  when: mysql_conf.stat.exists == False

- name: Adding .my.cnf for MySQL root Password Idempotency (RHEL/CentOS 6+)
  template:
    src="my.cnf.j2"
    dest={{ mysql_my_cnf }}
  when: mysql_conf.stat.exists == False

- name: Remove Anonymous MySQL Users (RHEL/CentOS 6+)
  mysql_user:
    name=''
    host={{ item }}
    state=absent
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: "{{ mysql_db_hosts }}"

- name: Creating RadiusDesk Database (RHEL/CentOS 6+)
  mysql_db:
    name={{ rd_db_name }}
    state=present
    login_user=root
    login_password={{ mysql_root_password }}

- name: Creating RadiusDesk Database on AWS RDS (RHEL/CentOS 6+)
  mysql_db:
    name={{ rd_db_name }}
    state=present
    login_user={{ aws_rds_user }}
    login_password={{ aws_rds_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
  when: enable_aws_rds_support

- name: Creating RadiusDesk Database User (RHEL/CentOS 6+)
  mysql_user:
    "name={{ rd_db_user }}
    password={{ rd_db_password }}
    priv={{ rd_db_name }}.*:ALL
    state=present
    login_user=root
    login_password={{ mysql_root_password }}
    host={{ item }}"
  with_items: "{{ mysql_db_hosts }}"

- name: Creating RadiusDesk Database User on AWS RDS (RHEL/CentOS 6+)
  mysql_user:
    "name={{ rd_db_user }}
    password={{ rd_db_password }}
    priv={{ rd_db_name }}.*:ALL
    state=present
    login_user={{ aws_rds_user }}
    login_password={{ aws_rds_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
    host={{ item }}"
  with_items: "{{ aws_rds_db_hosts }}"
  when: enable_aws_rds_support

- name: Copying RADIUSDesk Database SQL File for AWS RDS (RHEL/CentOS 6+)
  shell: cp -a {{ nginx_webroot }}/cake3/rd_cake/setup/db/rd.sql {{ temp_src_dir | quote }}/rd_aws.sql
  when: enable_aws_rds_support

- name: Updating RADIUSDesk Database SQL File for AWS RDS (RHEL/CentOS 6+)
  shell: sed -i.bk "s/DEFINER=\`root\`@\`localhost\`/DEFINER=CURRENT_USER /g" {{ temp_src_dir | quote }}/rd_aws.sql
  when: enable_aws_rds_support

- name: Importing RadiusDesk Database (RHEL/CentOS 6+)
  mysql_db:
    state=import
    name={{ rd_db_name }}
    target={{ nginx_webroot }}/cake3/rd_cake/setup/db/rd.sql
    login_user=root
    login_password={{ mysql_root_password }}

- name: Importing RadiusDesk Database to AWS RDS (RHEL/CentOS 6+)
  mysql_db:
    state=import
    name={{ rd_db_name }}
    target={{ temp_src_dir | quote }}/rd_aws.sql
    login_user={{ rd_db_user }}
    login_password={{ rd_db_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
  when: enable_aws_rds_support

- name: Updating RADIUSDesk Cake 2 Database Credentials (RHEL/CentOS 6+)
  template:
    src="rd/c2/database.php.j2"
    dest="{{ nginx_webroot }}/cake2/rd_cake/Config/database.php"

- name: Updating RADIUSDesk Cake 3 Database Credentials (RHEL/CentOS 6+)
  template:
    src="rd/c3/app.php.j2"
    dest="{{ nginx_webroot }}/cake3/rd_cake/config/app.php"
